package com.prompt2prd.analysis.domain;

public enum RequirementType {
    PRODUCT_GOAL,
    ROLE,
    FEATURE,
    USER_STORY,
    BUSINESS_RULE,
    EXCEPTION_SCENARIO,
    TECHNICAL_CONSTRAINT,
    DATA_MODEL,
    ACCEPTANCE_CRITERION,
    PAGE,
    API,
    IMPLEMENTATION_PHASE,
    CODING_AGENT_CONSTRAINT,
    NON_FUNCTIONAL_REQUIREMENT,
    ASSUMPTION,
    RISK_OPEN_ITEM,
    MISSING_INFORMATION
}
